name: Trigger EC2 Image Builder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region

    - name: Trigger EC2 Image Builder Pipeline
      run: |
        aws imagebuilder start-image-pipeline-execution --image-pipeline-arn "arn:aws:imagebuilder:us-east-1:500424735506:image-pipeline/blog-post-image-pipeline"
